Made a new text box for confirming added book
NaumVitanov/BookStore pull request #2
Opened 2022-05-02 15:55 UTC by NaumVitanov

2022-05-02 15:56 UTC, NaumVitanov commented on WinFormsApp1/Form1.cs
> +        private void Form1_Load(object sender, EventArgs e)
How did this show up and what does it do?

2022-05-04 06:39 UTC, ValentinoGechev requested changes
Review your logic and think how you can remove or use the Task.Delay method in another way.

2022-05-04 06:39 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +            textBox4.Text = "You added a new book!";
It makes no sense to tell the user "you've added a new book" before actually adding the book, because it might fail. For example, the Convert method can throw an exception if the user did not input a number, but some word.

2022-05-04 06:39 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +            catch (Exception )
You should specify the actual Exception in this case, not the base class. You can have different exceptions and the way it is currently written will catch all of them. For example if the **books** object is not initialized and you try to add "bookss" to it, it will throw a [System.NullReferenceException], but you would still MessageBox.Show "you must enter a number".

2022-05-04 06:39 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +            Task.Delay(1 * 1000).Wait();
Why do you need this?

2022-05-04 06:39 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +
remove this line

2022-05-04 06:39 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +                    }
Format please

2022-05-04 06:39 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +            textBox4.Text = String.Empty;
Think about this. First you say "book was added" then you try to add the book, it might fail it might not. And then you remove the text "book was added". The whole thing happens in a couple of milliseconds and the user will not be able to read anything. (actually now I understand why you have the Task.Delay, to stop the program for a second so the user can read it, am i right? But that's not how it's done)

2022-05-04 06:39 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +        private void Form1_Load(object sender, EventArgs e)
Just like a Console app has an entry point (the public static void Main(string[] args) method), the same way a Form of a desktop app has an entry point. So when you open the Form it will first enter in this method. and you can load some stuff for example. Or if you have a login , for example, you can add functionality in this method to say "Hello <user-name>" when the Form is opened.

2022-05-04 06:39 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +        private void label1_Click(object sender, EventArgs e)
Why do you need this method? Remove it.

2022-05-04 06:39 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +                Book bookss = new(textBox1.Text, Convert.ToInt32(textBox2.Text));
bookss? Please, practice your variable-naming skills :D

2022-05-04 17:56 UTC, ValentinoGechev approved these changes
Approved with suggestions

2022-05-04 17:56 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +                if (string.IsNullOrEmpty(textBox1.Text) | string.IsNullOrEmpty(textBox2.Text) | string.IsNullOrEmpty(textBox5.Text))
Nice, I like this, also it's good that you use the single "or" operator.  The difference is that the single " | " operator will evaluate both sides of the expression while the double operator " || " will only evaluate the left side if the expression returns true, meaning it will not check the other stuff if the first one returns true.

2022-05-04 17:56 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +                    MessageBox.Show("You must fill all of the requerd information to proceed");
required fields*

2022-05-04 17:56 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +
remove new line

2022-05-04 17:56 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +                    Book books2 = new(textBox1.Text, Convert.ToInt32(textBox2.Text), textBox5.Text);
Book book

2022-05-04 17:56 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +
new line

2022-05-04 17:56 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +            if (books.Count > x)
Haha, that's a smart way to check if the book was added, nice one. But there's no need to have this check. You can remove the "x" variable and this check and just move the "MessageBox.Show(..)" method right after line 30 (books.Add). If you don't go inside the catch, meaning there's not an exception being thrown, then you can be sure the book is added to the list, so no need for checking the count.

2022-05-04 17:56 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +                MessageBox.Show("You have succesufuly added a book!");
successfully*

2022-05-04 17:56 UTC, ValentinoGechev commented on WinFormsApp1/Form1.cs
> +                textBox3.Text = textBox3.Text + "Name of the book:" + Book.Name + Environment.NewLine + "Year of the book:" + Book.Year + Environment.NewLine + "Book Genre:" + Book.Genre + Environmen
foreach (var Book in books)

please use camelCase for variable names (start with small letter) and PascalCase for method/function names

2022-05-05 18:25 UTC, merged